### ISSUE TITLE
new symbols not showing up in Creature maker

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#22]
I have uploaded 6 symbols today and none of them show up at https://toolness.github.io/mystic-symbolic/?p=creature
Initially I thought maybe it wasn't recognizing spec layers with additional colors, so I made "fish_head_2" and "fish_tail_2" with the old-style spec layers, and they didn't show up either. So I made "head_bird" with the old-style spec layer, and it hasn't shown up either, so I assume the problem is unrelated to the spec layers and has a different cause.

**Comment by toolness** [comment]
Oo yeah, right now the problem is that the site follows a [crash early](https://www.quora.com/What-does-crash-early-mean-in-software-engineering) philosophy, where as soon as it encounters a color in the `specs` layer that it doesn't know how to deal with, it explodes.

You can actually see the exploding in the [Actions](https://github.com/toolness/mystic-symbolic/actions) tab of the project--note all the red "X"'s.  Each time you make a change to the repository, GitHub runs the code to rebuild the site, and if it fails, it will show a red "X".  If you click through to see the error log (which is quite confusing, so don't worry if you don't understand it), it looks like it exploded with the following error:

> `Error: Not sure what to do with specs path with fill "none"!`

So it encountered a path with no fill, which it didn't understand, and exploded.

I could alter the behavior to ignore stuff it doesn't understand, but be forewarned that the downside of that approach is that if you _accidentally_ use the wrong color for something, you won't really be given any feedback about it...

Anyways, I will add the code to recognize the additional spec layers soon, but in the meantime, a workaround would be to _remove_ the files containing the new-style spec layers until I add the new functionality.  Sorry I didn't mention this earlier!

**Comment by ninapaley** [comment]
OK I deleted the "bad" files and re-uploaded the "good" files and I can finally see fish heads in the creature maker. Whew!
