### ISSUE TITLE
unable to upload symbols

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#25]
I uploaded a batch of modified svg's with the dark red tail points added. That upload failed. Then I uploaded a single svg with the dark red tail point added. That upload failed. Then I removed the tail point and uploaded "infinity" again. That upload failed. I now assume my svg uploads are just gonna fail until something gets fixed.

**Comment by toolness** [comment]
Hmm, it looks like the culprit was `specs_empty.svg`, so I removed that and I think that fixed some things.  In the GitHub "Actions" tab if you click on a failed job and look at its log, amongst the gobbledygook it prints out each SVG it's adding:

![image](https://user-images.githubusercontent.com/124687/108748779-fa0ac800-750c-11eb-9490-58544a12a664.png)

Here it complains that it found an unexpected `<g>` in the specs layer (a `<g>` is the SVG element it adds for each layer in moho i think), and a few lines above it, it says it was adding `specs_empty.svg`... so that's how I knew that the problem was with that particular file.

**Comment by ninapaley** [comment]
Ahhh thanks! I forgot that file was still in that folder. Into the trash it goes so I don't make that mistake again.
