### ISSUE TITLE
Error: "Must have at least one bounding box"?

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#42]
Hmm, my most recent uploads didn't work:
![Screen Shot 2021-03-01 at 5 12 05 PM](https://user-images.githubusercontent.com/79212762/109571748-be926f80-7ab1-11eb-8c11-4f356dbc5021.png)
This is a puzzlement because the svg file most certainly has a bounding box, and all the other specs:
![Screen Shot 2021-03-01 at 5 16 40 PM](https://user-images.githubusercontent.com/79212762/109571933-02857480-7ab2-11eb-89de-b3816690d126.png)
It would be a puzzlement even if it didn't have a bounding box, since I've been able to upload many other symbols with no bounding box.

**Comment by ninapaley** [comment]
This just happened again, with another perfectly good symbol, "impossible_triangle". I made a toml file for it too. Can you investigate @toolness ?

**Comment by ninapaley** [comment]
Yup, something is broken. I can't upload any symbols any more. :(

**Comment by toolness** [comment]
Ohh it looks like there is an empty layer in the SVG called "halves" and my code wasn't prepared for empty layers!  I'll fix it, one sec.

**Comment by toolness** [comment]
Ok I think I fixed it!  Also just FYI the terminology the website builder uses is a bit funky: "bounding box" refers to the bounding box of an SVG, which it tries to calculate in order to make it easy to crop the SVGs to their actual sizes, rather than the size of your canvas in Moho. This is in contrast to "nesting area", which refers to the size of the nesting area.

In this case, my code was looking at the empty "halves" layer and trying to figure out what its bounding box was, which it couldn't do because the layer didn't have any shapes in it.  Now I've fixed it to just ignore empty layers though, so all should be well!
