### ISSUE TITLE
folder(s) for non-creature symbols, other assets

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#47]
Right now the folder called "svg" is where all the symbols and TOMLs for the Creature Maker go. But what about the "clouds" page? Or the "waves" page? Or other pages? I propose re-naming the svg folder and creating another folder(s) for other svg assets.

**Comment by toolness** [comment]
Ooo ya.

Maybe we should have a folder called `data` that contains any kind of SVG/TOML files used by the system, and under it have a subdirectory called `symbols` that has the creature symbols in it?

e.g. hierarchically:

* `data` directory
  * `symbols` directory
    * `eye.svg`
    * `eye.toml`
    * etc...

The waves page is actually a bit funky because it "hard-codes" the waves SVG into itself at [waves-page.jsx](https://github.com/toolness/mystic-symbolic/blob/main/lib/pages/waves-page.tsx).  This is because there were so many dynamic elements to it that it was easier to just do it that way than it was to slurp in an existing SVG file and manipulate its contents...  The downside of that though is that it's now impossible for you to change how the waves look (aside from the various sliders and stuff that are on that page of course).  We could potentially rework it to slurp in an SVG that you have in a directory that's a sibling of the `symbols` directory though...

**Comment by ninapaley** [comment]
I like that system! Can we call the big folder "assets" instead of "data"?

No worries about the waves, I think anything your code generates is better than an svg anyway!

**Comment by toolness** [comment]
ooh yeah i like assets!  cool let's go with that.  I think it will be easiest if I do the folder renaming/re-org from my end, just to make sure the website doesn't break in the process.  Are there any times of day you don't edit the assets?  I can try doing the renaming/re-org then.

**Comment by ninapaley** [comment]
Hmm, I'm editing assets tonight, and probably tomorrow also....If you get up early tomorrow, I should still be asleep since I'm an hour behind you. Early tomorrow morning?

**Comment by ninapaley** [comment]
Hey @toolness , tomorrow (Friday) I will be pretty busy and I can avoid uploading anything, if you want to re-name the folder(s). Let me know!

**Comment by toolness** [comment]
Ok this should be done now @ninapaley! Let me know if anything seems off to you...

**Comment by ninapaley** [comment]
Yay, thanks! Just one thing: weren't we gonna call it "assets" instead of "data"? Now is probably the time to change it! @toolness

**Comment by toolness** [comment]
Oh right! Sorry, just fixed it in e69ce202daf8bfbf786a3af74401ed9e11644627.
